import Head from 'next/head'
import Header from '@/componet/Header';
import RestaurantCards from '@/componet/RestaurantCards';

export default function Home() {

  return (
    <>
      <Head>
        <title>Open Table Resturant Reservation </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favico.ico" />
      </Head>
      <main className="w-screen min-h-screen bg-gray-100">
        <main className="bg-white max-w-screen-2xl">
          <Header />
          <main>
       <RestaurantCards />
          </main>
        </main>
      </main>
    </>
  )
}


