import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Open Table Resturant Reservation </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.PNG" />
      </Head>

      <main className='bg-gray-100 min-h-screen w-screen'>
        <main className=' max-w-screen-2xl m-auto bg-white mx-auto'>
          {
            /* 
            Begining of  Navbar 
            */
          }

          <nav className='bg-white p-2 flex justify-between'>
            <a href='' className='font-bold text-gray-700 text-2xl'>

              OpenTable
            </a>

            {/* singin and signout button */}

            <div>
              <div className='flex'>
                <button className='bg-cyan-600 text-white border p-1 px-4 rounded mr-3'>Sign In</button>
                <button className=' text-black border p-1 px-4 rounded mr-3'>Register</button>
              </div>
            </div>

          </nav>

          {
            /* 
            End of  Navbar 
            */
          }


          {/* header */}
          <div className='h-64 bg-gradient-to-r from-[#0f1f47] to-[#5f6984] p-2'>
            <div className='text-center mt-10'>
              <h1 className='text-white text-5xl font-bold mb-2'>
                Find yout table for any occation
              </h1>

            </div>

          </div>

        </main>
      </main>

    </>
  )
}
