import Head from 'next/head'
import Header from '@/componet/Header';
import RestaurantCards from '@/componet/RestaurantCards';

export default function Home() {

  return (
    <>
      <Head>
        <title>Open Table Resturant Reservation </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.PNG" />
      </Head>
      <main>
        <Header />
        <div className="py-3 px-36 mt-10 flex flex-wrap justify-start">
        <RestaurantCards />
      </div>
         
      </main>
    </>
  )
}
